src/java/cubisoft/carycob/managedBeans/PagoController.java
package cubisoft.carycob.managedBeans;

import cubisoft.carycob.entidades.Pago;
import cubisoft.carycob.managedBeans.util.JsfUtil;
import cubisoft.carycob.managedBeans.util.PaginationHelper;
import cubisoft.carycob.ejb.PagoFacade;
import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@ManagedBean(name = "pagoController")
@SessionScoped
public class PagoController implements Serializable {

    private Pago current;
    private DataModel items = null;
    @EJB
    private cubisoft.carycob.ejb.PagoFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public PagoController() {
    }
    
    /**
     * Elimina un pago
     * @autor: Carlos Delgadillo
     * @fecha: 15/04/2014
     */
    public void eliminarPago(){
        ejbFacade.remove(current);
    }

    public Pago getSelected() {
        if (current == null) {
            setSelected(new Pago());
            selectedItemIndex = -1;
        }
        return current;
    }

    private PagoFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {
                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        setSelected((Pago) getItems().getRowData());
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        setSelected(new Pago());
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PagoCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        setSelected((Pago) getItems().getRowData());
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PagoUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        setSelected((Pago) getItems().getRowData());
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("PagoDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            setSelected(getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0));
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Pago getPago(java.lang.String id) {
        return ejbFacade.find(id);
    }

    /**
     * @param current the current to set
     */
    public void setSelected(Pago current) {
        this.current = current;
    }

    @FacesConverter(forClass = Pago.class)
    public static class PagoControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            PagoController controller = (PagoController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "pagoController");
            return controller.getPago(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Pago) {
                Pago o = (Pago) object;
                return getStringKey(o.getIdPago());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Pago.class.getName());
            }
        }
    }
}

web/pago/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreatePagoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreatePagoLabel_idPago}" for="idPago" />
                    <p:inputText id="idPago" value="#{pagoController.selected.idPago}" title="#{bundle.CreatePagoTitle_idPago}" required="true" requiredMessage="#{bundle.CreatePagoRequiredMessage_idPago}"/>
                    <h:outputLabel value="#{bundle.CreatePagoLabel_monto}" for="monto" />
                    <p:inputText id="monto" value="#{pagoController.selected.monto}" title="#{bundle.CreatePagoTitle_monto}" required="true" requiredMessage="#{bundle.CreatePagoRequiredMessage_monto}"/>
                    <h:outputLabel value="#{bundle.CreatePagoLabel_factura}" for="factura" />
                    <p:selectOneMenu id="factura" value="#{pagoController.selected.factura}" required="true" requiredMessage="#{bundle.CreatePagoRequiredMessage_factura}">
                        <f:selectItems value="#{facturaController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreatePagoLabel_carga}" for="carga" />
                    <p:selectOneMenu id="carga" value="#{pagoController.selected.carga}" required="true" requiredMessage="#{bundle.CreatePagoRequiredMessage_carga}">
                        <f:selectItems value="#{cargaController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pagoController.create}" value="#{bundle.CreatePagoSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{pagoController.prepareList}" value="#{bundle.CreatePagoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/inicio" value="#{bundle.CreatePagoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pago/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditPagoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditPagoLabel_idPago}" for="idPago" />
                    <p:inputText id="idPago" value="#{pagoController.selected.idPago}" title="#{bundle.EditPagoTitle_idPago}" required="true" requiredMessage="#{bundle.EditPagoRequiredMessage_idPago}"/>
                    <h:outputLabel value="#{bundle.EditPagoLabel_monto}" for="monto" />
                    <p:inputText id="monto" value="#{pagoController.selected.monto}" title="#{bundle.EditPagoTitle_monto}" required="true" requiredMessage="#{bundle.EditPagoRequiredMessage_monto}"/>
                    <h:outputLabel value="#{bundle.EditPagoLabel_factura}" for="factura" />
                    <p:selectOneMenu id="factura" value="#{pagoController.selected.factura}" required="true" requiredMessage="#{bundle.EditPagoRequiredMessage_factura}">
                        <f:selectItems value="#{facturaController.itemsAvailableSelectOne}"/>
                    </p:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{pagoController.update}" value="#{bundle.EditPagoSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditPagoViewLink}"/>
                <br />
                <h:commandLink action="#{pagoController.prepareList}" value="#{bundle.EditPagoShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/inicio" value="#{bundle.EditPagoIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pago/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <f:view>
                <f:event listener="#{pagoController.prepareList()}" type="preRenderView" />
            </f:view>
            <h:outputText value="#{bundle.ListPagoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListPagoEmpty}" rendered="#{pagoController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{pagoController.items.rowCount > 0}">
                    <h:outputText value="#{pagoController.pagination.pageFirstItem + 1}..#{pagoController.pagination.pageLastItem + 1}/#{pagoController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{pagoController.previous}" value="#{bundle.Previous} #{pagoController.pagination.pageSize}" rendered="#{pagoController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{pagoController.next}" value="#{bundle.Next} #{pagoController.pagination.pageSize}" rendered="#{pagoController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{pagoController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPagoTitle_idPago}"/>
                            </f:facet>
                            <h:outputText value="#{item.idPago}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPagoTitle_monto}"/>
                            </f:facet>
                            <h:outputText value="#{item.monto}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPagoTitle_factura}"/>
                            </f:facet>
                            <h:outputText value="#{item.factura}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListPagoTitle_carga}"/>
                            </f:facet>
                            <h:outputText value="#{item.carga}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{pagoController.prepareView}" value="#{bundle.ListPagoViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{pagoController.prepareEdit}" value="#{bundle.ListPagoEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{pagoController.destroy}" value="#{bundle.ListPagoDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{pagoController.prepareCreate}" value="#{bundle.ListPagoCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/inicio" value="#{bundle.ListPagoIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/pago/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewPagoTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewPagoLabel_idPago}"/>
                    <h:outputText value="#{pagoController.selected.idPago}" title="#{bundle.ViewPagoTitle_idPago}"/>
                    <h:outputText value="#{bundle.ViewPagoLabel_monto}"/>
                    <h:outputText value="#{pagoController.selected.monto}" title="#{bundle.ViewPagoTitle_monto}"/>
                    <h:outputText value="#{bundle.ViewPagoLabel_factura}"/>
                    <h:outputText value="#{pagoController.selected.factura}" title="#{bundle.ViewPagoTitle_factura}"/>
                    <h:outputText value="#{bundle.ViewPagoLabel_carga}"/>
                    <h:outputText value="#{pagoController.selected.carga}" title="#{bundle.ViewPagoTitle_carga}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{pagoController.destroyAndView}" value="#{bundle.ViewPagoDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewPagoEditLink}"/>
                <br />
                <h:commandLink action="#{pagoController.prepareCreate}" value="#{bundle.ViewPagoCreateLink}" />
                <br />
                <h:commandLink action="#{pagoController.prepareList}" value="#{bundle.ViewPagoShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/inicio" value="#{bundle.ViewPagoIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>